#!/bin/bash
source _common.sh
source /usr/share/yunohost/helpers

#checking for hedscale user
check_headscale_user
#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression --message="Setting up source files..." --weight=1
# Download, check integrity, uncompress and patch the source from app.src
git config --system --add safe.directory $install_dir
git clone https://github.com/tale/headplane.git "$install_dir" --quiet

#chmod -R o-rwx "$install_dir"
#chown -R headplane:www-data "$install_dir"

#=================================================
# INSTALL DEPENDENCIES
#=================================================
ynh_script_progression --message="Installing dependencies..." --weight=2
nodejs_version=22
ynh_nodejs_install

#=================================================
# INSTALL Headplane
#=================================================
ynh_script_progression --message="Building $app... (this will take some time and resources!)" --weight=3
#ynh_exec_as_app npm install pnpm
pushd "$install_dir"
	npm install -g pnpm
    pnpm install
	pnpm build
popd
randomstr=$(ynh_string_random --length=16)

ynh_config_add --template="env" --destination="$install_dir/.env"

usermod -aG headscale headplane
chown -R headplane:headplane "$install_dir"

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression --message="Configuring NGINX web server..." --weight=4

# Create a dedicated NGINX config
ynh_config_add_nginx

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression --message="Adding system configurations related to $app..." --weight=5

# Create a dedicated systemd config
ynh_config_add_systemd

#=================================================
# ADD A CONFIGURATION
#=================================================
#ynh_script_progression --message="Adding a configuration file..."

#ynh_add_config --template="../conf/config.js" --destination="$install_dir/config/config.js"

#chmod 600 "$install_dir/config/config.js"
#chown $app "$install_dir/config/config.js"


#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Starting a systemd service..." --weight=6

# Start a systemd service
ynh_systemctl --service=$app --action="start" --log_path="systemd"

#=================================================
# APPLY FOLDER RIGHTS
#=================================================

#chgrp -R www-data $install_dir


#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Installation of $app completed" --last
