#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# REMOVE THE NGINX CONFIGURATION
#=================================================
ynh_script_progression "Removing nginx web server configuration..."

ynh_config_remove_nginx

ynh_remove_systemd_config

ynh_exec_warn_less rm -rf $install_dir